//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationAppraisal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppraisalDBEntities : DbContext
    {
        public AppraisalDBEntities()
            : base("name=AppraisalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appraisal> Appraisals { get; set; }
        public DbSet<AppraisalGoal> AppraisalGoals { get; set; }
        public DbSet<AppraisalPolicy> AppraisalPolicies { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<GoalCategory> GoalCategories { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
    }
}
