//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationAppraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        public Appraisal()
        {
            this.AppraisalGoals = new HashSet<AppraisalGoal>();
        }
    
        public int ID { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<AppraisalGoal> AppraisalGoals { get; set; }
    }
}
