//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalGoal
    {
        public int ID { get; set; }
        public string ManagerComments { get; set; }
        public string EmployeeComments { get; set; }
        public int ManagerRating { get; set; }
        public int EmployeeRating { get; set; }
        public int AppraisalID { get; set; }
        public int GoalsID { get; set; }
    
        public virtual Appraisal Appraisal { get; set; }
        public virtual Goal Goal { get; set; }
    }
}
