//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public Goal()
        {
            this.AppraisalGoals = new HashSet<AppraisalGoal>();
        }
    
        public int ID { get; set; }
        public string GoalDescription { get; set; }
        public int GoalCategoryID { get; set; }
    
        public virtual ICollection<AppraisalGoal> AppraisalGoals { get; set; }
        public virtual GoalCategory GoalCategory { get; set; }
    }
}
